checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  jsroot@*:
    dependencies:
      jspdf: "*"
      svg2pdf.js: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
