
---
apiVersion: v1
kind: Service
metadata:
  name: phoenixapp
spec:
   ports:
     - port: 80
       nodePort: 30000
       targetPort: app-port
       protocol: TCP
   selector: 
        app: phoenixapp
   type: LoadBalancer
