/**
 * Generate the version info shown on the Phoenix landing page.
 *
 * The version comes from lerna.json (fixed-mode, bumped by `lerna publish` and
 * matching the vX.Y.Z git tags). The commit and release flag come from git when
 * available - every git call degrades gracefully, since builds must not break
 * when git is missing, .git is absent (Docker) or the clone is shallow (CI).
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const repoRoot = path.resolve(__dirname, '..');
const outputFile = path.resolve(
  repoRoot,
  'packages/phoenix-ng/projects/phoenix-app/src/environments/version.ts',
);

/** Run a git command, returning its trimmed output or null if it fails. */
function git(...args) {
  try {
    return execFileSync('git', args, {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return null;
  }
}

const { version } = require(path.resolve(repoRoot, 'lerna.json'));

// GITHUB_SHA covers the case where the workflow checked out without git history.
const commit =
  git('rev-parse', '--short=8', 'HEAD') ??
  (process.env.GITHUB_SHA ?? '').slice(0, 8);

// `git describe --exact-match` only succeeds when HEAD is itself tagged. Note
// that a shallow clone has no tags, so a release build needs fetch-depth: 0.
// PHOENIX_VERSION_IS_RELEASE is an escape hatch for the GitHub Pages build,
// which Lerna runs after bumping lerna.json but before creating the tag.
const isRelease =
  process.env.PHOENIX_VERSION_IS_RELEASE === '1' ||
  process.env.GITHUB_REF_TYPE === 'tag' ||
  git('describe', '--tags', '--exact-match', 'HEAD') !== null;

fs.writeFileSync(
  outputFile,
  `// Generated by scripts/generate-version.js during build. Do not edit.
export const versionInfo = {
  version: '${version}',
  commit: '${commit}',
  isRelease: ${isRelease},
};
`,
);

console.log(
  `Generated version.ts: ${version}${commit ? ` (${commit})` : ''}${
    isRelease ? ' [release]' : ''
  }`,
);
